# docker-compose.yml
services:
  asta:
    build: .
    container_name: asta-fantacalcio-live
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
